eureka:
  client:
    eureka-server-port: 8761
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 60000
##This property has to be true, so that it uses the IP address, instead of localhost or 127.0.0.1
    prefer-ip-address: true

spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://localhost:3306/nozama_user_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
#    username: nozama_dba
#    password: nozama19

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/
    
  cloud:
    gateway:
      routes:
      - id: nozama-productservice
        uri: http://localhost:8082
        predicates:
        - Path=/category/**
      - id: nozama-productservice
        uri: http://localhost:8082
        predicates:
        - Path=/product/**
      - id: nozama-orderservice
        uri: http://localhost:8094
        predicates:
        - Path=/order/**
      - id: nozama-userservice
        uri: http://localhost:8081
        predicates:
        - Path=/user/**
      - id: nozama-userauthservice
        uri: http://localhost:8089
        predicates:
        - Path=/auth/**  
      - id: nozama-cartservice
        uri: http://localhost:8088
        predicates:
        - Path=/cart/** 
      - id: nozama-configservice
        uri: http://${configservice_host:localhost}:${configservice_port:8888}
        predicates:
        - Path=/config/**
      - id: nozama-addressservice
        uri: http://localhost:8092
        predicates:
        - Path=/address/**

logging:
  file: 
    path: "../log" 
    name: "${logging.file.path}/${spring.application.name:nozama}_log.log"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
        
